version: "3.3"
services:
  mongodb:
    container_name: docker-mongo
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      - MONGODB_USER=""
      - MONGODB_PASS=""
    volumes:
      - ./mongo_data:/data/db